/*	SCCS Id: @(#)date.h	3.4	2002/02/03 */

/* This source file is generated by 'makedefs'.  Do not edit. */
#define BUILD_DATE "Tue Feb  9 15:02:22 2016"
#define BUILD_TIME (1455055342L)

#define VERSION_NUMBER 0x03040300UL
#define VERSION_FEATURES 0x003e0c46UL
#define IGNORED_FEATURES 0x00800000UL
#define VERSION_SANITY1 0x211b017dUL
#define VERSION_SANITY2 0xb8d24950UL

#define VERSION_STRING "3.4.3"
#define VERSION_ID \
 "Unix NetHack Version 3.4.3 - last build Tue Feb  9 15:02:22 2016."
#define JVERSION_ID \
 "Unix JNetHack Version 0.8.0 - last build Tue Feb  9 15:02:22 2016."

